### ISSUE TITLE
02 - Hello UX Markup.md - Confusing wording around subclassing GraphicsTheme

### ISSUE THREAD

**Issue by cbaggers** [fusetools/handbook-docs#1]
The $(GraphicsTheme) section talks about subclassing the graphicstheme but the example subclasses basictheme.
Talking with you guys it sounds like subclassing basictheme is a good idea but the handbook doesn't explain the difference. Add a sentence to clarify this.

**Comment by petterroea** [comment]
I'l have a look at it

**Comment by petterroea** [comment]
It appears that the text has been removed anyways \o/

Closing
