### ISSUE TITLE
Document new Uno project changes

### ISSUE THREAD

**Issue by ollef** [fusetools/handbook-docs#100]
See the Uno changelog for version 0.23

**Comment by sebbert** [comment]
@ollef I can't see anything regarding the unoproj format in 0.23's changelog. What are these changes?

**Comment by ollef** [comment]
Hmm, can't remember anymore, sorry. Maybe the stuff under 0.21.0/Build system? It might be a good idea to go through the changelog quickly and see if there's anything that is not documented but seems worthy of it.

**Comment by sebbert** [comment]
Alright :+1:
