### ISSUE TITLE
PageControl documentation is outdated

### ISSUE THREAD

**Issue by Tapped** [fusetools/handbook-docs#110]
GoBack and GoForward etc. are stuff mentioned in the handbook that doesn't exist anymore

**Comment by sebbert** [comment]
@Tapped What else than GoBack/GoForward has been removed? "etc." doesn't tell me much.

**Comment by mortoray** [comment]
Those functions should still be there...

...I did an upgrade to Pagecontrol yesterday. I'll write the additions/changes in an issue tomorrow.

**Comment by Tapped** [comment]
@mortoray, oh I see, they aren't properties anymore. The GoBack and GoForward is used as properties in the UX doc

**Comment by Tapped** [comment]
How are users supposed to call these methods from UX? (may be a dumb question)

**Comment by sebbert** [comment]
You're talking about **Can**GoBack/Forward. I agree, it makes no sense to document then in the handbook.
