### ISSUE TITLE
ambiguity of terms in 'Hello, UX Markup!'

### ISSUE THREAD

**Issue by cbaggers** [fusetools/handbook-docs#117]
> Fuse can be used in two primary ways:
> - Creating apps or prototypes with cross-platform JavaScript logic
> - Creating components, UI views and designs for native apps

In the above text the , `designs for native apps` make it sound like the components you are making can be used in different kinds of apps than the ones described in the first bullent-point.

Currently we can only make components that can be used in fuse apps, so maybe 
> - Creating components, UI views and designs for other apps

**Comment by cbaggers** [comment]
Wait.. maybe this means our ability to use native ui elements?
it's a bit confusing

**Comment by sebbert** [comment]
Fixed
