### ISSUE TITLE
RangeAdapter doc

### ISSUE THREAD

**Issue by mortoray** [fusetools/handbook-docs#130]
Requires https://github.com/fusetools/fuselibs/pull/1565
@petterroea will likely have an example of a custom switch using this

## RangeAdapter

The `RangeAdapter` can be used to adjust the range of values used in bindings. This allows finer control over animations such as `Timeline` and `...Animation` triggers.

- `Source` the value to be adapted. This value is always updated directly, the `RangeAdapter` does not store any value internall.
- `SourceRangeMin` the minimum value to map to on the source
- `SourceRangeMax` the maximum value to map to on the source
...TBD... (side-tracked support)

**Comment by petterroea** [comment]
I have an example, so i can write docs about this when done.

**Comment by kristianhasselknippe** [comment]
@petterroea did you get started on this? We need it soon :)

**Comment by petterroea** [comment]
https://github.com/fusetools/handbook-docs/pull/163
