### ISSUE TITLE
Update handbook to account for Visual refactor

### ISSUE THREAD

**Issue by nekronos** [fusetools/handbook-docs#134]
Visuals
	Primitives, Image, Shape, and TextControl, should not have any child nodes. This is being deprecated and the ability will be removed. It can only be partially enforced at the UX level (unfortunately with a not-so-clean error message for now). These nodes need to be leaf nodes for optimization reasons.

	A common previous scenario might have been to add a Rectangle to a Text node:

	  <Text Alignment="Center" Padding="5">
	      <Rectangle Layer="Background" Color="0,1,1,1"/>
	  </Text>
	This should now be done using a wrapping Panel instead:

	  <Panel Alignment="Center">
	      <Text Alignment="Center" Padding="5"/>
	      <Rectangle Layer="Background" Color="0,1,1,1"/>
	  </Panel>
	Shapes (Circle, Ellipse, Rectangle, Star, RegularPolygon, Path) are no longer implemented with visual children in Graphics mode. They are directly drawn in the semantic control type. This will not likely affect any user code.

	Padding has been fixed in some shapes. This may change the positioning of shapes that have padding.
	Node.InvalidateVisual is no longer virtual, override the OnInvalidateVisual function instead. This gives Node better control over when it is called, and how to invalidate
	Node.IsVisualInvalid has been removed as the invalidation system is active (at time of invalidation), thus nothing should (or did) check that flag

^ Fix handbook to take this into account ^

**Comment by mortoray** [comment]
We're not sure now if we really want to disable support for this. @duckers indicates that having children of things like `Rectangle` is desired.  But perhaps not for `Text` (though it makes no difference in the code).

**Comment by sebbert** [comment]
@mortoray @nekronos Is this ticket still valid?

**Comment by petterroea** [comment]
Got a response, closing: 

`@petterroea: I don’t think so. I think we’re agree that visuals can contain children, especially the shapes. Try to avoid making children of Text in any examples though.`
