### ISSUE TITLE
Update pagecontrol docs to specify the fact that children don't have to be pages any more

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/handbook-docs#143]
https://www.fusetools.com/learn/fuse#keyword-pagecontrol

Was pointed out in this thread.

**Comment by sebbert** [comment]
@kristianhasselknippe  Which thread? Also, this is already mentioned:

In this context, the term "page" does not necessarily mean Page, but refers to any child of the PageControl that participates in navigation."

**Comment by kristianhasselknippe** [comment]
@sebbert I think the paragraph should be changed so that it never talks about page. That way, the clarification is not needed.

**Comment by sebbert** [comment]
Alright
