### ISSUE TITLE
Searching for "screen orientation" only results in a bunch of bug reports

### ISSUE THREAD

**Issue by bentstamnes** [fusetools/handbook-docs#157]
It would be nice if there was at least one mention of how to set the screen orientation in .unoproj-files outside of people complaining that it doesn't work. :) So, either in the handbook or in the guides.

**Comment by bentstamnes** [comment]
@sebbert is probably the right one.

**Comment by sebbert** [comment]
I'm currently rewriting the entire unoproj docs, so I'll give this some special love in the process

**Comment by sebbert** [comment]
This has its own "master" ticket, so I'll close this one.
