### ISSUE TITLE
Make all ux names into links

### ISSUE THREAD

**Issue by cbaggers** [fusetools/handbook-docs#2]
Everywhere that we use ``..someName..`` for a UX element, that name item should also be a link to the UX documentation. It sounds excessive but it's great to be able to jump from where you are in the document and know clicking back will return you to that same point.

**Comment by petterroea** [comment]
I don't get what you mean by this. Are you saying you want every time we mention a variable, that it is a link to the documentation for the type of the variable?

@kristianhasselknippe Worth implementing? What do you think? The issue is a bit old, so the style of the docs might of changed.

**Comment by sebbert** [comment]
I think this issue rather belongs in cortex

**Comment by petterroea** [comment]
As far as i understood, i think he wants us to use the $() syntax instead of the \`\` syntax on variable names, so i don't see how it belongs there

**Comment by kristianhasselknippe** [comment]
@petterroea but that wouldn't make any sense as variable names can't be made into global link targets.

@cbaggers: Would you care to comment on this? Is it still relevant?
