### ISSUE TITLE
Dead link in PageControl chapter

### ISSUE THREAD

**Issue by knatten** [fusetools/handbook-docs#22]
In "We actually already built most of the behavior of the PageControl from scratch in Basic navigation. ", the link to https://www.fusetools.com/learn/fuse#ref-basic-navigation is dead.

**Comment by tanordheim** [comment]
Some woes after updating our Markdown engine last night. The URL `https://www.fusetools.com/learn/fuse#ref-basic-navigation` has changed to `https://www.fusetools.com/learn/fuse#keyword-basic-navigation`, and the existing docs have been updated to reflect this.
