### ISSUE TITLE
`LayoutChange` is deprecated,

### ISSUE THREAD

**Issue by mortoray** [fusetools/handbook-docs#28]
The doc needs to be updated to remove `LayoutChange` from the transforms. the replacements for Move are:

- `PositionChange` - the change in position of a element within it's parent
- `WorldPositionChange` - the change in position relative to the entire display. This is the closest replacement to `LayoutChange`

For Resize:

- `SizeChange` - the change in size of the element

For Scale:

- `SizeChange` - the factor of the size change of the element

**Comment by petterroea** [comment]
Waiting for `SizeFactor` to be merged from one of Mortoray's branches before working more on this.

**Comment by petterroea** [comment]
https://github.com/fusetools/handbook-docs/pull/48
