### ISSUE TITLE
Animation timeline

### ISSUE THREAD

**Issue by mortoray** [fusetools/handbook-docs#29]
I've created a draft guide for understanding animation timelines.  Minimal graphs have also been included.

https://github.com/Outracks/Sandbox/tree/master/Sandboxes/mortoray/Nov2015/AnimDoc

**Comment by petterroea** [comment]
I'l put this into the part about animations :)

**Comment by petterroea** [comment]
Bent said he could do the illustrations for this, but not before it has been proofread.

**Comment by petterroea** [comment]
Allright, this ticket has been here for a while, and has been thrown back and forward a bit.

Last time i mentioned it in _docs_, there was questions on whether or not this had place in the docs for animation. I was planning to put it at the start of the section on animations, as a nice primer to how it works.

@kristianhasselknippe What do you think? I'l start a discussion about it on docs again, and see what people think.

**Comment by petterroea** [comment]
Replies from people say two main things:

 * This could be it's own article
* This should be restructured for easier reading.

**Comment by bentstamnes** [comment]
What's the progress on this? @yupferris has created a new tutorial video that goes into details on `<Timeline>` but right now we have zero docs on the subject.

**Comment by kristianhasselknippe** [comment]
@petterroea did you write anything on this yet. I think some version of mortorays stuff could be quite useful as a guide or part of the handbook. I'll add a little something about the `Timeline` class, since this is covering a whole lot more.

**Comment by bentstamnes** [comment]
@kristianhasselknippe I discussed this with @petterroea at some length earlier, I think it was on Slack. Just making some notes on the general buildup of the piece, like: only doing one property at a time to explain in a waterfall way, instead of laying multiple elements on the reader at once.

**Comment by kristianhasselknippe** [comment]
@bentstamnes sounds good

**Comment by petterroea** [comment]
Yep, talking about it on slack. Current plan is to move it to a guide

**Comment by petterroea** [comment]
Moved to guides repo
