### ISSUE TITLE
Mention SizeFactor in "Resize" and "Scale" once merged 

### ISSUE THREAD

**Issue by petterroea** [fusetools/handbook-docs#47]
https://github.com/fusetools/handbook-docs/issues/28

**Comment by petterroea** [comment]
Done in #85

**Comment by sebbert** [comment]
The PR isn't merged yet. In the future, add "resolves #<issue number>" to the description of the pull request to make it automatically close on merge.

**Comment by sebbert** [comment]
Nevermind, it's already documented in #72, although @petterroea's PR improves it.
