### ISSUE TITLE
Document `OnBackButton` and `OnKeyPress`

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/handbook-docs#80]
https://www.fusetools.com/learn/fuse/ux/fuse/triggers/onkeypress
https://www.fusetools.com/learn/fuse/ux/fuse/triggers/onbackbutton

And how they can be used to interact with hardware buttons like androids back and options buttons.

**Comment by petterroea** [comment]
Currently writing an experiment on it. My phone does not have a menu button, so slightly delayed by that. Will charge a test device and test on thursday

**Comment by petterroea** [comment]
Written in #98. Close this when #98 is merged.

**Comment by sebbert** [comment]
@petterroea For next time, you can write `fixes #98` in the description of a pull request to automatically close an issue when it is merged.
