### ISSUE TITLE
Add documentation about WebView.SnapMaxScroll /MinScroll

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/handbook-docs#93]

**Comment by sebbert** [comment]
@kristianhasselknippe I can't find those properties in latest fuselibs master. Is this ticket still valid?

**Comment by petterroea** [comment]
Update on this?

**Comment by kristianhasselknippe** [comment]
@Sunjammer might know for sure?

**Comment by Sunjammer** [comment]
I didn't know WebView had those properties!? Haha

**Comment by petterroea** [comment]
https://github.com/fusetools/fuselibs/blob/531d6b3a5f211f2c8f468d554fd7c1abbfefcb90/Source/Fuse.Controls/WebView/WebView.uno

Doesn't look like it exists any more. Closing.
