### ISSUE TITLE
Add doc for TextInputActionTriggered

### ISSUE THREAD

**Issue by nekronos** [fusetools/handbook-docs#94]
`<TextInputActionTriggered />` is triggered when returnkey on iOS/Android is pressed, needs to be documented + example :)

**Comment by nekronos** [comment]
https://www.fusetools.com/community/forums/howto_discussions/actionstylesearch

**Comment by nekronos** [comment]
<App Theme="Basic">

		<ClientPanel>

			<StackPanel>
				<JavaScript>

					function search_pressed (argument) {
						console.log("Search pressed");
					}

					module.exports = {
						search_pressed:search_pressed
					};

				</JavaScript>

				<TextInput Height="40" ux:Name="search_box" PlaceholderText="search text" ActionStyle="Search" PlaceholderColor="#A9D4B0" >
					<TextInputActionTriggered>
						<Callback Handler="{search_pressed}" />
					</TextInputActionTriggered>
				</TextInput>

			</StackPanel>
		
		</ClientPanel>

	</App>

**Comment by mortoray** [comment]
It's just a style choice, but some of our users might like the shorter JS syntax for exports:
```
exports.search_pressed = function(argument) {
    console.log("Search pressed");
}
```

**Comment by sebbert** [comment]
Merged
